apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: dashboard-wazuh.ssegning.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dashboard
            port:
              number: 443
  - host: manager-wazuh.ssegning.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wazuh-workers
            port:
              number: 1514
